name: CD

on:
  release:
    types: [ published ]

jobs:

  publish-package:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - name: Build project
        run: npm run build
      - name: Set NPM credentials
        run: >-
          npm config set _auth ${{ secrets.NPM_TOKEN }}
          && npm config set registry https://registry.npmjs.org/
          && npm config set always-auth=true
      - name: Publish to NPM (dry-run)
        run: npm publish --access public --dry-run
      - name: Publish to NPM
        run: npm publish --access public
